[project]
name = "tmdb-service"
version = "1.2.0"
description = "TMDB Service"
requires-python = ">=3.12"
authors = [{ name = "jessielw" }]
license = { file = "LICENSE" }
keywords = ["tmdb", "api", "cli", "service", "automatic"]
urls = { "Source" = "https://github.com/jessielw/TMDB-Service", "Tracker" = "https://github.com/jessielw/TMDB-Service/issues" }
dependencies = [
    "aiohttp==3.14.3",
    "aiofiles==25.1.0",
    "aiocron==2.1",
    "python-dotenv==1.2.3",
    "psycopg2-binary==2.9.13",
    "sqlalchemy==2.0.52",
    "fastapi==0.141.1",
    "uvicorn[standard]==0.53.0",
]

[project.optional-dependencies]
dev = ["ruff"]

[tool.ruff]
line-length = 88
include = ["tmdb_service/**/*.py", "examples/**/*.py"]

[tool.ruff.lint]
select = ["I"]

[tool.basedpyright]
include = ["tmdb_service", "examples"]
typeCheckingMode = "standard"

[tool.setuptools.package-data]
"tmdb_service.tmdb_to_csv" = ["sql/*.sql"]
